<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCoreRateLimit" Version="5.0.0" />
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="FluentValidation" Version="11.11.0" />
		<PackageReference Include="MailKit" Version="4.14.1" />
		<PackageReference Include="MediatR" Version="12.4.1" />
		<PackageReference Include="MimeKit" Version="4.14.0" />
		<PackageReference Include="QuestPDF" Version="2025.12.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\HealthcareSystem.Domain\HealthcareSystem.Domain.csproj" />
	</ItemGroup>
</Project>